version: '3.9'

services:
  brawl-game:
    image: dockergointeens/frontend-games:latest
    ports:
      - target: 9000
        published: 9000
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.service == config-server"
          - "node.labels.env == prod"
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        max_failure_ratio: 0
        failure_action: rollback
      rollback_config:
        parallelism: 1
        max_failure_ratio: 0
        failure_action: continue
